# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StylishApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'FBSDKCoreKit'  
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'FBSDKPlacesKit'
pod 'FBSDKMessengerShareKit'
  # Pods for StylishApp

  target 'StylishApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StylishAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


